# Generated by Django 5.0.4 on 2024-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARFood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='gltf',
            field=models.FilePathField(path='ARFood/static/models/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
