# Generated by Django 5.0.4 on 2024-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARFood', '0003_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='gltf',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
